[[backend-sql]]
= SQL

[abstract]
--
This section describes the SQL backend and GraphDDL.
--


[[backend-sql-pgds]]
== SQL PGDS

The most powerful PGDS is the SQL PGDS.
It allows the extraction of graphs from any system that understands SQL.
In particular, Hive and JDBC are the two interfaces used.

The SQL PGDS is configured using a JSON file which contains parameters necessary to connect across JDBC or to Hive.

.Example SQL PGDS configuration
====

[source, scala]
----
include::{snippets-dir}/SqlPGDS.scala[tags=create-sql-pgds]
----

This example creates a SQL PGDS configured to read both from Hive and from an embedded H2 SQL database.

====

The graphs that a SQL PGDS stores are defined by their Graph DDL, which expresses graph schema and mappings from views and tables available in the configured data sources.

.Graph DDL example (located at /path/to/my/Graph.ddl)
====

[source, "graph ddl"]
----
include::{snippets-res-dir}/SqlPGDS.ddl[tags=full-example]
----

The above Graph DDL requires two tables (with columns): `view_KNOWS (start_id, end_id, since)` and `view_Persons (id, name)` to be present in the catalog of `myH2Source.myH2Schema` (the `myH2Schema` schema of the H2 database).

====

[[backend-sql-pgds-tables]]
=== Tables and columns

* The referenced tables are required to contain all the columns referenced in the Graph DDL, but may also contain additional columns; these will not be selected.
* By default, there is a case-insensitive mapping between the label properties to table columns, such that a table `foo(BAR1 varchar, BAR2 bigint)` will map into a label `(Foo {bar1: STRING, BAR2: INTEGER})`.
  The case in the graph will follow the case specified in the graph schema, as Cypher is case sensitive when it comes to property keys.


include::backend-sql-graphddl.adoc[leveloffset=+1]

