[[backend-graphddl]]
= Graph DDL (Data Definition Language)

[abstract]
--
Placeholder abstract.
--

Graph DDL enables importing SQL tabular data into a property graph in Spark.
It is common that the data inside relational databases is or can be modelled as a graph, but the data is often not formatted correctly to be directly exploited as such.

Make sure to read the section on making graphs from tables before reading this section.
That background knowledge is necessary.


[[graphddl-overview]]
== Overview

Graph DDL makes it possible to create two kinds of structures:

* *graphs* that may contain:
** type definitions, such as
*** _element types_ with defined properties
*** _node types_ composed of element types
*** _relationship types_ composed of element types
** _table mappings_ that link node and relationship types to tables and columns in a SQL data source

* *graph types* that allow for:
** extracting type definitions from graphs into reusable structures
** graphs to refer to a named graph type (i.e. inheritance)

Both graphs and graph types are named and referenced by their name. Named graphs are made available in the property graph catalog through registering a SQL Property Graph Datasource (see <<backend-sql-pgds>>) with the referenced Graph DDL.

To describe the graph type and its components, a Cypher-style ASCII art pattern syntax is used.
The goal is to reflect the information captured in an Entity-Relationship conceptual data model in an intuitive graph pattern shorthand.

The syntax for mapping tabular data into nodes and relationships in a graph is more like SQL, using concepts like correlation names (table aliases) and joins to express how table rows and columns map to nodes, edges and properties.


=== Standards

Graph DDL has been developed in close collaboration with the SQL standards committee that is working on an official SQL extension for property graphs with the next release of the SQL standard (SQL:202x).
This also intersects with the standards process currently being undertaken for developing an official graph query language (GQL) where Cypher is one of the major input languages considered.
Graph DDL could become part of this standard.

Interoperability with SQL, and forward compatibility with a future GQL language, are important goals for both the Cypher for Apache Spark project and CAPS.
Graph DDL is one way in which the two worlds of SQL and graph querying can be tied together.
This parallels the ability to use SQL tables as inputs to Cypher queries and to post-process Cypher query tabular result sets using SQL.


[[graphddl-approach]]
== Approach

As we described in the earlier sections, once you have data in a "tables for labels" format, CAPS can lift that data into a graph and you can query it with Cypher.
We have already covered how that is done if the data in question is already a set of DataFrames, or something that can conveniently be made a DataFrame (like a CSV file).

However, for a relational database, one would approach this as follows:

. Take existing operational tables and use SQL's `CREATE VIEW` to transform the data into "tables for labels" format via views.
  In this way the data stays fresh, and no schema modifications to the underlying database are necessary.
. For relationships, the simplest mapping is to create views which form link tables that model how a particular set of nodes are connected to another particular set.
  Other relationship mapping options are also supported.
. Use Graph DDL statements to define graph types.
. Use Graph DDL statements to define the equivalent of the mapping step.
. Use the SQL PGDS to pull graphs directly out of the relational database.


[[graphddl-motivation]]
== Hello World example

The Graph DDL has two kind of components: *graphs* and *graph types*.

We will start with a simple "Hello World" example that demonstrates the definition of a graph.
Comments are marked with two dashes (`--`), like in SQL.

.Create a graph from our movie database.
[source, graphddl]
----
SET SCHEMA sql_server.movie_db

CREATE GRAPH movie_graph (

  -- element types
  Person   ( name STRING, born INTEGER ),
  Movie    ( title STRING, released INTEGER ),
  ACTED_IN,

  -- node types with mapping
  (Person) FROM view_person,
  (Movie)  FROM view_movie (name AS title, year AS released),

  -- relationship types with mapping
  (Person)-[ACTED_IN]->(Movie) FROM view_appearances rel
    START NODES (Person) FROM view_person p JOIN ON p.id = rel.person_id
    END NODES   (Movie)  FROM view_movie m  JOIN ON m.id = rel.movie_id
)
----

In this second example, we extract local type definitions from the graph into a separate graph type which is then referred to by the graphs.
Using this approach, multiple graph definitions might reuse the same graph type.

.Create two graphs with the same graph type but from different regional movie databases.
[source, graphddl]
----
SET SCHEMA sql_server.movie_db

CREATE GRAPH TYPE movie_graph_type (
  -- element types
  Person   ( name STRING, born INTEGER ),
  Movie    ( title STRING, released INTEGER ),
  ACTED_IN,

  -- node types
  (Person),
  (Movie),

  -- relationship types
  (Person)-[ACTED_IN]->(Movie)
)

CREATE GRAPH movie_graph_US OF movie_graph_type (

  -- node types with mapping
  (Person) FROM view_person_US,
  (Movie)  FROM view_movie_US (name AS title, year AS released),

  -- relationship types with mapping
  (Person)-[ACTED_IN]->(Movie) FROM view_appearances_US rel
    START NODES (Person) FROM view_person_US p JOIN ON p.id = rel.person_id
    END NODES   (Movie)  FROM view_movie_US m  JOIN ON m.id = rel.movie_id
)

CREATE GRAPH movie_graph_EU OF movie_graph_type (

  -- node types with mapping
  (Person) FROM view_person_EU,
  (Movie)  FROM view_movie_EU (name AS title, year AS released),

  -- relationship types with mapping
  (Person)-[ACTED_IN]->(Movie) FROM view_appearances_EU rel
    START NODES (Person) FROM view_person_EU p JOIN ON p.id = rel.person_id
    END NODES   (Movie)  FROM view_movie_EU m  JOIN ON m.id = rel.movie_id
)
----

[[graphddl-structure]]
== Structure

In the subsequent sections we will describe all the Graph DDL components in detail.

[[graphddl-element-type]]
=== Element type

An element type is referred to by its _name_, often called its _label_, and forms the basis for node and relationship types.
An element type may contain property definitions, similar to a column definition in SQL. 
A property definition is composed of the property name and its data type.
Element types are declared the same way regardless if they are to be used as node or relationship types.
//Element types are hierarchical and allow single and multiple inheritance.

Element types can be declared either globally or locally within a graph type or within a graph.

.Local element type definition with two properties:
[source, graphddl]
----
MyType (
  property STRING,
  data INTEGER?
)
----

.Global element type definitions are prefixed with `CREATE ELEMENT TYPE`:
[source, graphddl]
----
CREATE ELEMENT TYPE MyType (
  property STRING,
  data INTEGER?
)
----

Possible data types reflect a subset of the Cypher type system. 
Currently supported types are:
`STRING`, `INTEGER`, `FLOAT` and `BOOLEAN` as well as their nullable counterparts, i.e. `STRING?`, `INTEGER?`, `FLOAT?` and `BOOLEAN?`.

[[graphddl-node-type]]
=== Node type

A node type is composed of one or more element types and inherits all the properties defined by the referred element types.
Overlapping property names are allowed as long as the property data type is the same.

[NOTE]
====
While the property graph data model supports nodes without labels, this is currently not expressible in the Graph DDL implementation for CAPS.
====

Assume the following element types:
[source, graphddl]
----
Person ( name STRING, birthyear INTEGER ),
Actor  ( no_oscars INTEGER ),
Movie  ( title STRING )
----

We can compose node types by referring to element types in scope:

[source, graphddl]
----
(Movie),        -- node type with one element type
(Actor, Person) -- node type with two element types
----

[[graphddl-rel-type]]
=== Relationship type

A relationship type contains three parts: A start node type, a single element type as well as an end node type.

Assume the following element types and node types:

[source, graphddl]
----
-- element types
Person  ( name STRING, birthyear INTEGER ),
Actor   ( no_oscars INTEGER ),
Movie   ( title STRING ),
ACTED_IN ( salary FLOAT ),
-- node types
(Movie)
(Actor, Person),
----

We can declare relationship types by referring to node and element types in scope:

[source, graphddl]
----
(Actor, Person)-[ACTED_IN]->(Movie)
----

[[graphddl-graph-type]]
=== Graph type

A graph type contains element, node and relationship types. 
A graph type is always named (e.g. `movie_graph_type`).
Definitions within a graph type may refer to global element types.
If a type is already globally defined, a local definition shadows a global definition.

.Example graph type definition with references to global element types (Person):
[source, graphddl]
----
CREATE ELEMENT TYPE Person ( name STRING, birthyear INTEGER )

CREATE GRAPH TYPE movie_graph_type (
  -- element types
  Actor    ( no_oscars INTEGER ),
  Movie    ( title STRING, released INTEGER ),
  ACTED_IN,

  -- node types
  (Actor, Person),
  (Movie),

  -- relationship types
  (Actor, Person)-[ACTED_IN]->(Movie)
)
----

[[graphddl-graph]]
=== Graph

A graph may contain element, node and relationship types.
In addition, table mappings can be attached to node and relationship types.

A graph is always named. 
Definitions within a graph may refer to global element types.

Optionally, a graph refers to a graph type. 
In that case, element types defined in the graph type can be referenced.
If a type is already defined outside of the graph scope, local definitions shadow global definitions.

Table mappings are used to map SQL tables (or views) into node / relationship types within the graph.
The syntax for those mappings follow this outline:

.Node type definition with table mapping
[source, graphddl]
----
-- node type with mapping
<node-type> FROM <sql-table> (<column1> AS <property1>, ...),
<node-type> FROM <sql-table> (<column1> AS <property1>, ...),
  ...,

-- relationship type with mapping
<relationship-type>
    FROM <sql-table> <rel-alias> (<column1> AS <property1>, ...)  -- mapping 1
      START NODES (<node-type>) FROM <sql-table> <start-alias>
        JOIN ON <start-alias>.<column> = <rel-alias>.<column>
      END NODES (<node-type>) FROM <sql-table> <end-alias>
        JOIN ON <end-alias>.<column> = <rel-alias>.<column>,

    FROM <sql-table> <rel-alias> (<column1> AS <property1>, ...)  -- mapping 2
        ...,

<relationship-type> -- the next relationship type
    FROM ...
)
----

Here, `<node-type>` declares a node type and the `<sql-table>` denotes the name of a SQL table (see <<graphddl-referencing-tables>>).
The optional `(<column1> AS <property1>, ...)` may be used to map a column to a property with a different name.
The default behaviour is to look for a column with the same name as the property. This lookup is case-sensitive.

Relationship types also map to SQL tables with optional column-to-property mappings.
In contrast to the node type, mappings for start and end nodes must be specified.
`JOIN` syntax is used to connect the corresponding SQL tables. 
Table names are aliased to simplify the join expressions.

[NOTE]
====
Note that the columns used for the join expression may reach outside of the declared property set for the relationship or its end nodes; any column present on the SQL table is valid.
====

As can be observed in the outline, it is possible to map relationships from many different SQL tables, using different start and end node declarations and join expressions.
Use a comma separator between each pair of `FROM` definitions, and also between mappings for different relationship types.
Multiple mappings for a single node or relationship type result in a union of the single mappings.

.Create a graph from our movie database.
[source, graphddl]
----
CREATE GRAPH movie_graph (

  -- element types
  Person   ( name STRING, born INTEGER ),
  Movie    ( title STRING, released INTEGER ),
  ACTED_IN,

  -- node types with mapping
  (Person) FROM view_person,
  (Movie)  FROM view_movie (name AS title, year AS released),

  -- relationship types with mapping
  (Person)-[ACTED_IN]->(Movie) FROM view_appearances rel
    START NODES (Person) FROM view_person p JOIN ON p.id = rel.person_id
    END NODES   (Movie)  FROM view_movie m  JOIN ON m.id = rel.movie_id
)
----

[[graphddl-referencing-tables]]
== Referencing SQL tables and views

Within Graph DDL, SQL tables are identified using a three-part identifier, i.e. `<database>.<schema>.<table>`.
In order to use simple table names within mappings, a `SET SCHEMA <database>.<schema>` statement can be used in between graph and graph type definitions.

[NOTE]
====
In the SQL Property Graph Datasource (see <<backend-sql-pgds>>), the `<database>` refers to a SQL datasource config which points to an actual SQL database.
====

.Using relative and absolute table identifiers
[source, graphddl]
----
SET SCHEMA sql_server.movie_db

CREATE GRAPH movie_graph (
 (Person) FROM view_person,                     -- resolves to sql_server.movie_db.view_person
 (Movie)  FROM db2_server.movie_db.view_person, -- resolves to db2_server.movie_db.view_person
 ...
)
----


[[graphddl-usage]]
== How to use Graph DDL in CAPS

The Graph DDL is a part of the SQL Property Graph Datasource, and used in conjunction with it.
Please see <<backend-sql-pgds>> for information on how to configure and use it.
